#define BC_CMD_RESET_AVR            0
#define BC_CMD_TVP_GET_STATUS       1
#define BC_CMD_ADV_GET_STATUS       2
#define BC_CMD_TVP_NEXT_INPUT       3
#define BC_CMD_DSP_SEL              4
#define BC_CMD_SET_AMBI_STATUS      5
#define BC_CMD_GET_AMBI_STATUS      6
#define BC_CMD_SET_NC_RGB           7
#define BC_CMD_SET_MAX_RGB          8
#define BC_CMD_SET_LPF              9
#define BC_CMD_SET_BRIGHTNESS      10
#define BC_CMD_SET_OFFSET_RGB      11
#define BC_CMD_SET_LOGLEVEL        12
#define BC_CMD_SET_SIG_SEARCH      13
#define BC_CMD_SET_SLEEP_TOUT      14
#define BC_CMD_SET_CHANNEL_LED_NUM 15
#define BC_CMD_SET_CHANNEL_DATA    16
#define BC_CMD_GET_CHANNEL_LED_NUM 17
#define BC_CMD_RESET_TO_BTLDR_AVR  18
#define BC_CMD_GET_VERSION_INFO    19
#define BC_CMD_SET_SIM_YCBCR_DATA  20
#define BC_CMD_GET_DSP_SEL         21
#define BC_CMD_SET_TTY_BIN         22
#define BC_CMD_GET_TTY_BIN         23
